import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import ReactProvider from "./redux/ReactProvider";

const LexendSans = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={LexendSans.variable}>
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        />
      </head>
      <body className="antialiased">
        <ReactProvider>
          <div id="portal-root"></div>
          {children}
        </ReactProvider>
      </body>
    </html>
  );
}
